"""catopt_core.laws — rewrite laws and graph passes, split by domain.

* :mod:`catopt_core.laws.base` — the ``R`` rewrite constructor plus the
  shared check-hook machinery (``_SHAPE_MEMO``, ``_shape_of``, small
  term predicates).
* :mod:`catopt_core.laws.tensor` — the tensor-algebra laws:
  ``SIMPLIFICATION_RULES``, ``CATEGORICAL_RULES``, ``SDPA_FOLD_RULES``,
  ``ALL_RULES`` / ``all_rules()``.
* :mod:`catopt_core.laws.scan` — the scan-monoid law sets: ``SCAN_LAWS``
  (dense affine carrier) and ``SCAN_DIAG_LAWS`` (diagonal-affine).
* :mod:`catopt_core.laws.pairing` — the non-local passes over the whole
  e-graph (pairing, weight sharing).  These are diagram-level passes,
  not equational laws.

This package is the canonical rewrite surface — the historical
``catopt_core.rules`` module (and its ``catopt.rules`` alias) is gone.
"""

# Public surface (in ``__all__``) plus the private side-condition /
# memo helpers historically reachable through the removed
# ``catopt_core.rules`` shim (and its ``catopt.rules`` alias).  The
# private names are re-exported (hence ``noqa: F401``) so
# ``catopt_core.laws._x`` keeps resolving, but stay out of ``__all__``.
from catopt_core.laws.base import (  # noqa: F401
    _SHAPE_MEMO,
    R,
    _is_channel_scale,
    _is_row_scale,
    _is_scalar,
    _shape_of,
)
from catopt_core.laws.pairing import (  # noqa: F401
    _CONV_ATTR_KEYS,
    _pair_shared_input,
    _term_has_var,
    _wshape,
    pair_shared_input_convs,
    pair_shared_input_linears,
    share_duplicate_param_slices,
    share_duplicate_params,
)
from catopt_core.laws.scan import (  # noqa: F401
    _AFFD_UNIT,
    AFF_ASSOC,
    AFF_ASSOC_REV,
    AFF_COMPOSE_UNFOLD,
    AFF_LIFT,
    AFF_LIFT_STEP,
    AFF_UNLIFT,
    AFFD_ASSOC,
    AFFD_ASSOC_REV,
    AFFD_COMPOSE_UNFOLD,
    AFFD_LIFT,
    AFFD_LIFT_POST,
    AFFD_LIFT_POST_SWAP,
    AFFD_LIFT_STEP,
    AFFD_LIFT_STEP_POST,
    AFFD_LIFT_STEP_POST_SWAP,
    AFFD_LIFT_STEP_SWAP,
    AFFD_LIFT_SWAP,
    AFFD_LIFT_UNIT,
    AFFD_LIFT_UNIT_POST,
    AFFD_LIFT_UNIT_STEP,
    AFFD_LIFT_UNIT_STEP_POST,
    AFFD_UNLIFT,
    SCAN_DIAG_LAWS,
    SCAN_LAWS,
    _affd_state_like,
    _affd_unit_state_like,
    _derive_affd_unit,
)
from catopt_core.laws.tensor import (  # noqa: F401
    _QK_SCORES,
    _QKV_CAT,
    _REPEAT_KV,
    _REPEAT_V,
    ALL_RULES,
    ASSOC_ADD,
    ASSOC_LINEAR,
    ASSOC_LINEAR_BIAS,
    ASSOC_LINEAR_BIAS_REV,
    ASSOC_MATMUL,
    ASSOC_MATMUL_REV,
    ASSOC_MUL,
    CATEGORICAL_RULES,
    COMM_ADD,
    COMM_MUL,
    DISTRIBUTE_MUL,
    DOUBLE_NEG,
    FACTOR_MUL,
    GQA_ABSORB,
    ID_ADD,
    ID_MUL,
    LINEAR_CHANNEL_SCALE,
    LINEAR_CHANNEL_SCALE_REV,
    LINEAR_ROW_SCALE,
    LINEAR_ROW_SCALE_REV,
    NATURALITY_SCALAR,
    NATURALITY_SCALAR_REV,
    PARALLEL_MUL_FUSE,
    POW_TO_SQUARE,
    QKV_FUSE,
    QKV_FUSE_ASYM,
    RIGHT_DISTRIBUTE,
    RIGHT_FACTOR,
    RIGHT_FACTOR_LINEAR,
    SDPA_FOLD_RULES,
    SILU_EXPAND,
    SILU_MUL_FORM,
    SIMPLIFICATION_RULES,
    SQUARE_EXPAND,
    SQUARE_TO_POW,
    SUB_TO_ADD,
    SWIGLU_FUSE,
    WEIGHT_DISTRIBUTE,
    WEIGHT_DISTRIBUTE_LINEAR,
    WEIGHT_FACTOR,
    WEIGHT_FACTOR_LINEAR,
    _check_gqa_absorb,
    _check_linear_bias_compose,
    _check_repeat_chain,
    _check_score_transpose,
    _check_sdpa_base,
    _check_sdpa_mf,
    _check_sdpa_mf_scaled,
    _check_sdpa_scaled,
    _check_softmax_dim,
    _const_val,
    _derive_scale_div,
    _derive_scale_mul,
    _derive_scale_one,
    _derive_split_sizes,
    _head,
    _head_v,
    _make_sdpa_fold_rules,
    _scale_of,
    all_rules,
)

__all__ = [
    "AFFD_ASSOC",
    "AFFD_ASSOC_REV",
    "AFFD_COMPOSE_UNFOLD",
    "AFFD_LIFT",
    "AFFD_LIFT_POST",
    "AFFD_LIFT_POST_SWAP",
    "AFFD_LIFT_STEP",
    "AFFD_LIFT_STEP_POST",
    "AFFD_LIFT_STEP_POST_SWAP",
    "AFFD_LIFT_STEP_SWAP",
    "AFFD_LIFT_SWAP",
    "AFFD_LIFT_UNIT",
    "AFFD_LIFT_UNIT_POST",
    "AFFD_LIFT_UNIT_STEP",
    "AFFD_LIFT_UNIT_STEP_POST",
    "AFFD_UNLIFT",
    "AFF_ASSOC",
    "AFF_ASSOC_REV",
    "AFF_COMPOSE_UNFOLD",
    "AFF_LIFT",
    "AFF_LIFT_STEP",
    "AFF_UNLIFT",
    "ALL_RULES",
    "ASSOC_ADD",
    "ASSOC_LINEAR",
    "ASSOC_LINEAR_BIAS",
    "ASSOC_LINEAR_BIAS_REV",
    "ASSOC_MATMUL",
    "ASSOC_MATMUL_REV",
    "ASSOC_MUL",
    "CATEGORICAL_RULES",
    "COMM_ADD",
    "COMM_MUL",
    "DISTRIBUTE_MUL",
    "DOUBLE_NEG",
    "FACTOR_MUL",
    "GQA_ABSORB",
    "ID_ADD",
    "ID_MUL",
    "LINEAR_CHANNEL_SCALE",
    "LINEAR_CHANNEL_SCALE_REV",
    "LINEAR_ROW_SCALE",
    "LINEAR_ROW_SCALE_REV",
    "NATURALITY_SCALAR",
    "NATURALITY_SCALAR_REV",
    "PARALLEL_MUL_FUSE",
    "POW_TO_SQUARE",
    "QKV_FUSE",
    "QKV_FUSE_ASYM",
    "RIGHT_DISTRIBUTE",
    "RIGHT_FACTOR",
    "RIGHT_FACTOR_LINEAR",
    "SCAN_DIAG_LAWS",
    "SCAN_LAWS",
    "SDPA_FOLD_RULES",
    "SILU_EXPAND",
    "SILU_MUL_FORM",
    "SIMPLIFICATION_RULES",
    "SQUARE_EXPAND",
    "SQUARE_TO_POW",
    "SUB_TO_ADD",
    "SWIGLU_FUSE",
    "WEIGHT_DISTRIBUTE",
    "WEIGHT_DISTRIBUTE_LINEAR",
    "WEIGHT_FACTOR",
    "WEIGHT_FACTOR_LINEAR",
    "R",
    "all_rules",
    "pair_shared_input_convs",
    "pair_shared_input_linears",
    "share_duplicate_param_slices",
    "share_duplicate_params",
]
