"""catopt.laws — rewrite laws and graph passes, split by domain.

* :mod:`catopt.laws.base` — the ``R`` rewrite constructor plus the
  shared check-hook machinery (``_SHAPE_MEMO``, ``_shape_of``, small
  term predicates).
* :mod:`catopt.laws.tensor` — the tensor-algebra laws:
  ``SIMPLIFICATION_RULES``, ``CATEGORICAL_RULES``, ``SDPA_FOLD_RULES``,
  ``ALL_RULES`` / ``all_rules()``.
* :mod:`catopt.laws.scan` — the scan-monoid law sets: ``SCAN_LAWS``
  (dense affine carrier) and ``SCAN_DIAG_LAWS`` (diagonal-affine).
* :mod:`catopt.laws.pairing` — the non-local passes over the whole
  e-graph (pairing, weight sharing).  These are diagram-level passes,
  not equational laws.

``catopt.rules`` remains as a thin compatibility shim re-exporting
this surface; new code should import from ``catopt.laws``.
"""

from catopt.laws.base import R
from catopt.laws.pairing import (
    pair_shared_input_convs,
    pair_shared_input_linears,
    share_duplicate_param_slices,
    share_duplicate_params,
)
from catopt.laws.scan import (
    AFF_ASSOC,
    AFF_ASSOC_REV,
    AFF_COMPOSE_UNFOLD,
    AFF_LIFT,
    AFF_LIFT_STEP,
    AFF_UNLIFT,
    AFFD_ASSOC,
    AFFD_ASSOC_REV,
    AFFD_COMPOSE_UNFOLD,
    AFFD_LIFT,
    AFFD_LIFT_POST,
    AFFD_LIFT_POST_SWAP,
    AFFD_LIFT_STEP,
    AFFD_LIFT_STEP_POST,
    AFFD_LIFT_STEP_POST_SWAP,
    AFFD_LIFT_STEP_SWAP,
    AFFD_LIFT_SWAP,
    AFFD_LIFT_UNIT,
    AFFD_LIFT_UNIT_POST,
    AFFD_LIFT_UNIT_STEP,
    AFFD_LIFT_UNIT_STEP_POST,
    AFFD_UNLIFT,
    SCAN_DIAG_LAWS,
    SCAN_LAWS,
)
from catopt.laws.tensor import (
    ALL_RULES,
    ASSOC_ADD,
    ASSOC_LINEAR,
    ASSOC_LINEAR_BIAS,
    ASSOC_LINEAR_BIAS_REV,
    ASSOC_MATMUL,
    ASSOC_MATMUL_REV,
    ASSOC_MUL,
    CATEGORICAL_RULES,
    COMM_ADD,
    COMM_MUL,
    DISTRIBUTE_MUL,
    DOUBLE_NEG,
    FACTOR_MUL,
    GQA_ABSORB,
    ID_ADD,
    ID_MUL,
    LINEAR_CHANNEL_SCALE,
    LINEAR_CHANNEL_SCALE_REV,
    LINEAR_ROW_SCALE,
    LINEAR_ROW_SCALE_REV,
    NATURALITY_SCALAR,
    NATURALITY_SCALAR_REV,
    PARALLEL_MUL_FUSE,
    POW_TO_SQUARE,
    QKV_FUSE,
    QKV_FUSE_ASYM,
    RIGHT_DISTRIBUTE,
    RIGHT_FACTOR,
    RIGHT_FACTOR_LINEAR,
    SDPA_FOLD_RULES,
    SILU_EXPAND,
    SILU_MUL_FORM,
    SIMPLIFICATION_RULES,
    SQUARE_EXPAND,
    SQUARE_TO_POW,
    SUB_TO_ADD,
    SWIGLU_FUSE,
    WEIGHT_DISTRIBUTE,
    WEIGHT_DISTRIBUTE_LINEAR,
    WEIGHT_FACTOR,
    WEIGHT_FACTOR_LINEAR,
    all_rules,
)

__all__ = [
    "AFFD_ASSOC",
    "AFFD_ASSOC_REV",
    "AFFD_COMPOSE_UNFOLD",
    "AFFD_LIFT",
    "AFFD_LIFT_POST",
    "AFFD_LIFT_POST_SWAP",
    "AFFD_LIFT_STEP",
    "AFFD_LIFT_STEP_POST",
    "AFFD_LIFT_STEP_POST_SWAP",
    "AFFD_LIFT_STEP_SWAP",
    "AFFD_LIFT_SWAP",
    "AFFD_LIFT_UNIT",
    "AFFD_LIFT_UNIT_POST",
    "AFFD_LIFT_UNIT_STEP",
    "AFFD_LIFT_UNIT_STEP_POST",
    "AFFD_UNLIFT",
    "AFF_ASSOC",
    "AFF_ASSOC_REV",
    "AFF_COMPOSE_UNFOLD",
    "AFF_LIFT",
    "AFF_LIFT_STEP",
    "AFF_UNLIFT",
    "ALL_RULES",
    "ASSOC_ADD",
    "ASSOC_LINEAR",
    "ASSOC_LINEAR_BIAS",
    "ASSOC_LINEAR_BIAS_REV",
    "ASSOC_MATMUL",
    "ASSOC_MATMUL_REV",
    "ASSOC_MUL",
    "CATEGORICAL_RULES",
    "COMM_ADD",
    "COMM_MUL",
    "DISTRIBUTE_MUL",
    "DOUBLE_NEG",
    "FACTOR_MUL",
    "GQA_ABSORB",
    "ID_ADD",
    "ID_MUL",
    "LINEAR_CHANNEL_SCALE",
    "LINEAR_CHANNEL_SCALE_REV",
    "LINEAR_ROW_SCALE",
    "LINEAR_ROW_SCALE_REV",
    "NATURALITY_SCALAR",
    "NATURALITY_SCALAR_REV",
    "PARALLEL_MUL_FUSE",
    "POW_TO_SQUARE",
    "QKV_FUSE",
    "QKV_FUSE_ASYM",
    "RIGHT_DISTRIBUTE",
    "RIGHT_FACTOR",
    "RIGHT_FACTOR_LINEAR",
    "SCAN_DIAG_LAWS",
    "SCAN_LAWS",
    "SDPA_FOLD_RULES",
    "SILU_EXPAND",
    "SILU_MUL_FORM",
    "SIMPLIFICATION_RULES",
    "SQUARE_EXPAND",
    "SQUARE_TO_POW",
    "SUB_TO_ADD",
    "SWIGLU_FUSE",
    "WEIGHT_DISTRIBUTE",
    "WEIGHT_DISTRIBUTE_LINEAR",
    "WEIGHT_FACTOR",
    "WEIGHT_FACTOR_LINEAR",
    "R",
    "all_rules",
    "pair_shared_input_convs",
    "pair_shared_input_linears",
    "share_duplicate_param_slices",
    "share_duplicate_params",
]
